version: '2'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
  app:
    ## read php image from our custom docker image ##
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      ## copy project files to /var/www ##
      - .:/var/www
    working_dir: /var/www

  db:
    image: mysql:8.0
    ## expose the mysql port to our machine so we can access it from any mysql-client like TablePlus ##
    ports:
      - "3388:3306"
    ## keep mysql data on localhost so we don't lose them ##
    volumes:
      - ./docker-volumes-data/db:/var/lib/database
    environment:
      MYSQL_DATABASE: mrcs
      MYSQL_ROOT_PASSWORD: 'Mrcs'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 'Mrcs'
      MYSQL_ROOT_PASSWORD: 'Mrcs'

  redis:
      image: redis
      volumes:
        ## keep redis data on localhost so we don't lose them ##
        - ./docker-volumes-data/redis:/data
